# Generated by Django 5.1.2 on 2024-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('T-Shirt', 'T-Shirt'), ('Jacket', 'Jacket')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, default='No Description!', max_length=100, null=True),
        ),
    ]
