# Generated by Django 5.1.2 on 2024-10-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_products_category_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
