# Generated by Django 5.1.2 on 2024-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_products_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
