# Generated by Django 5.1.2 on 2024-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_tags_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
