# Generated by Django 5.1.2 on 2024-10-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_message', models.CharField(blank=True, max_length=35, null=True)),
                ('middle_message', models.CharField(blank=True, max_length=35, null=True)),
                ('right_message', models.CharField(blank=True, max_length=35, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
