# Generated by Django 5.1.2 on 2024-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_homemessages_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemessages',
            name='show',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False, null=True),
        ),
    ]
