# Generated by Django 5.1.2 on 2024-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_indexbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexbox',
            name='sened_date',
            field=models.DateField(auto_now=True),
        ),
    ]
